
version: '3.8'

services:
  mysql:
    image: mysql:9.0.1
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge

# type nul > docker-compose.yml

# docker-compose up -d

# docker exec -it mysql-server mysql -uroot -p

# CREATE DATABASE medac;

# Use medac

#CREATE TABLE alumnos (
#    id INT AUTO_INCREMENT PRIMARY KEY,
#    nom VARCHAR(100),
#    classe VARCHAR(50),
#    note DECIMAL(5, 2)
#);

#INSERT INTO alumnos (nom, classe, note) VALUES ('Alice', 'Informática', 18.50);
#INSERT INTO alumnos (nom, classe, note) VALUES ('Bob', 'Física', 15.75);
#INSERT INTO alumnos (nom, classe, note) VALUES ('Charlie', 'Informática', 17.00);



